### ISSUE TITLE
Documentación de la clase coordenada

### ISSUE THREAD

**Issue by arsa-dev** [MauronMP/PMP_IV#12]
Tras hablar con @JJ, hemos visto que sería interesante conocer un poco más el significado de la clase así como de sus propiedades, para saber que es cada una y poder hacer un docstring en cada elemento. Te adjunto el enlace al fichero de la clase:

https://github.com/arsa-dev/PMP_IV/blob/ar-implement-objetivo-2/pmp_iv/models/coordenada.py

**Comment by MauronMP** [comment]
Clase coordenada establece en un perímetro una zona delimitada una área, siendo x e y coordenada de un cuadrado de 3x3.
