### ISSUE TITLE
Documentación de la clase fecha

### ISSUE THREAD

**Issue by arsa-dev** [MauronMP/PMP_IV#14]
Tras hablar con @JJ, hemos visto que sería interesante conocer un poco más el significado de la clase así como de sus propiedades, para saber que es cada una y poder hacer un docstring en cada elemento. Te adjunto el enlace al fichero de la clase:

https://github.com/arsa-dev/PMP_IV/blob/ar-implement-objetivo-2/pmp_iv/models/fecha.py

**Comment by MauronMP** [comment]
Clase fecha sirve para poder segmentar los datos por meses y tener registros por días, semanas o meses.

**Comment by arsa-dev** [comment]
@MauronMP actualmente no se podría determinar la semana del mes con las propiedades que hay, solamente se podría segmentar por día de la semana y por meses. ¿Sería necesario añadir alguna otra propiedad para las semanas? De ser así, ¿qué valores tendría, algo como {Primera, Segunda, Tercera, Cuarta}?

**Comment by MauronMP** [comment]
Cierto, podría implementarse, pero para este milestone no es necesario, tal y como está me parece correcto, de momento sólo necesito trabajar sobre los días y meses

**Comment by arsa-dev** [comment]
Okey perfecto, lo dejo sin implementar por el momento
