### ISSUE TITLE
Documentación de la clase fwi

### ISSUE THREAD

**Issue by arsa-dev** [MauronMP/PMP_IV#15]
Tras hablar con @JJ, hemos visto que sería interesante conocer un poco más el significado de la clase así como de sus propiedades, para saber que es cada una y poder hacer un docstring en cada elemento. Te adjunto el enlace al fichero de la clase:

https://github.com/arsa-dev/PMP_IV/blob/ar-implement-objetivo-2/pmp_iv/models/fwi.py

**Comment by MauronMP** [comment]
La clase FWI contiene campos usados para los estudios de los riesgos de incendio, son atributos que ya se usan en estudio de incendios previos y tienen ya establecido unos límites. Para entenderlo en más profundidad te dejo  [este enlace](https://wikifire.wsl.ch/tiki-index91f7.html?page=Fine+fuel+moisture+code)
