### ISSUE TITLE
Validación usando metaestructura

### ISSUE THREAD

**Issue by arsa-dev** [MauronMP/PMP_IV#16]
Tras hablar en clase con @JJ, hemos visto que sería interesante sacar a un fichero de configuración todas las constantes que tenemos para validación en los modelos, así se podrían ajustar esas constantes en diferentes instalaciones o si en algún momento cambiara algún valor, como por ejemplo el máximo de 45º de temperatura en un verano intenso. ¿Que te parece si creo un fichero en el módulo pmp_iv.config que contenga todas las constantes y luego se usen para la validación?

**Comment by MauronMP** [comment]
De acuerdo, lo veo bien

**Comment by arsa-dev** [comment]
Genial @MauronMP, me pongo con ello en ese caso

**Comment by arsa-dev** [comment]
@MauronMP, @JJ, echadle cuando podáis un vistazo [al commit](https://github.com/arsa-dev/PMP_IV/commit/a263cf0dceb4d1d2eeefd34ec4962a44f7ef5a7c) referenciado a ver como lo veis, he implementado un pequeño sistema de validación simple que permite configurar las distintas validaciones de forma cómoda desde el fichero `pmp_iv.config.model_validation`. Además para resolver un problema de dependencias circulares, he sacado los enumerables utilizados en `pmp_iv.models.fecha` al espacio `pmp_iv.enums`.
