### ISSUE TITLE
Implementación de una clase para la fase model building

### ISSUE THREAD

**Issue by MauronMP** [MauronMP/PMP_IV#26]
Partiendo de la necesidad del HU0 #7, se necesita a partir de la clase EDA que se requiere en el issue #25, se quiere implementar una clase que estime la correlación entre los datos sesgados.

Se quiere implementar la correlación de Pearson con la fórmula de [la siguiente página](https://www.statisticshowto.com/probability-and-statistics/correlation-coefficient-formula/)

**Comment by MauronMP** [comment]
Se usará para el desarrollo de esta clase la librería mencionada en #27.

**Comment by JJ** [comment]
"Implementación de una clase" no plantea un problema.
En *todos* los milestones, *todos* los issues tienen que plantear problemas.

**Comment by JJ** [comment]
> Partiendo de la necesidad del HU0 #7, se necesita a partir de la clase EDA que se requiere en el issue #25, se quiere implementar una clase que estime la correlación entre los datos sesgados.
> 
> Se quiere implementar la correlación de Pearson con la fórmula de [la siguiente página](https://www.statisticshowto.com/probability-and-statistics/correlation-coefficient-formula/)

Si es la correlación de Pearson, eso debería estar en el código, no en el issue.
