### ISSUE TITLE
Definición de tecnología a usar

### ISSUE THREAD

**Issue by arsa-dev** [MauronMP/PMP_IV#8]
Hola @MauronMP,

ya veo que está aprobado el PR https://github.com/MauronMP/PMP_IV/pull/4, por lo que puedes mergearlo aunque haya algún punto que mejorar tal y como comenta @JJ.

Abro hilo de discusión para definir la tecnología y comenzar el desarrollo del objetivo 2 en un nuevo PR. ¿En qué tecnología crees que es mejor desarrollar tu proyecto? ¿Tienes alguna buena práctica o consideración a tener en cuenta de cara a la implementación además de lo que se especifica en el [M0](https://github.com/MauronMP/PMP_IV/milestone/2)?

**Comment by MauronMP** [comment]
Buenas, acabo de ver que ha aprobado el PR, te comento, la idea principalmente es desarrollarlo en python, ya que quiero usar jupyter notebook con librerias de machine-learning, para, finalmente, exportar los datos y gráficos a PDF. Principalmente, voy a basarme en repositorios parecidos a [este](https://github.com/aravind9722/Forest-fire_Prediction)

**Comment by JJ** [comment]
> Buenas, acabo de ver que ha aprobado el PR, te comento, la idea principalmente es desarrollarlo en python, ya que quiero usar jupyter notebook con librerias de machine-learning, para, finalmente, exportar los datos y gráficos a PDF. Principalmente, voy a basarme en repositorios parecidos a [este](https://github.com/aravind9722/Forest-fire_Prediction)

Eso lo vas a hacer seguramente fuera de la asignatura. Si es por eso únicamente, yo no lo aconsejaría. Para el caso, también trabajan con Jupyter Notebooks julia y R.

**Comment by arsa-dev** [comment]
@MauronMP si te parece bien puedo seguir [la guía](https://www.giulianopertile.com/blog/why-you-should-use-dataclasses-in-python/) que comenta @JJ si continúas pensando en hacerlo en python, y crear esas dataclasses así como un pequeño programa que cree instancias de ellas. Y luego podrías utilizarlas de cara a seguir lógicas similares como la del proyecto que citas, en ese proyecto no he visto que haya ninguna clase, directamente utiliza lo que le llega desde el consumidor de la api usando listas.

**Comment by MauronMP** [comment]
Buenas, me parece bien entonces que sigas la guía de JJ, no había visto esa opción.

**Comment by arsa-dev** [comment]
Hola @MauronMP, he implementado las clases definidas en el [M0](https://github.com/MauronMP/PMP_IV/milestone/2), aunque para las definiciones 4 a 8 no tengo muy claro que eso sean clases, parecen más simplemente validación de valores pero no sabría en que clase o lugar habría que definirlos. O debo de crearlas como clases con una única propiedad por ejemplo `value` y que cuente con esa validación

**Comment by JJ** [comment]
@arsa-dev sería conveniente que, como hemos dicho en clase, abrieras antes un issue para discutirlo; normalmente no se hacen PRs contra una hU directamente, salvo que esté muy claro. En todo caso, es cosa de @MauronMP decidir.

**Comment by MauronMP** [comment]
Buenas @arsa-dev, he visto los ficheros que has creado, de momento me parece que están bien, igualmente necesito comprobarlo y mirarlo con más detenimiento. Respecto a los cambios que mencionó JJ, los cambiaré. 
Lo único que si me haría falta es que crees el issue como ha mencionado y respecto a lo que mencionas de las definiciones 4 a 8, siguiendo la manera del [fwi.py](https://github.com/MauronMP/PMP_IV/blob/3a9b44fab7f00e375dc12102e068fe01d32c7d19/models/fwi.py) que has creado podrías hacer algo parecido con las definiciones del 4 al 8.

**Comment by JJ** [comment]
> @arsa-dev sería conveniente que, como hemos dicho en clase, abrieras antes un issue para discutirlo; normalmente no se hacen PRs contra una hU directamente, salvo que esté muy claro. En todo caso, es cosa de @MauronMP decidir.

Es cierto que este era el issue que has abierto, no lo vi en su contexto, perdona. Sí sería conveniente, en todo caso, que tuvieras issues diferentes para la tecnología y para la implementación; así se puede hacer referencia de forma independiente.

**Comment by arsa-dev** [comment]
De acuerdo @JJ, creo uno nuevo para debatir las cuestiones de implementación
